In [ ]:
# array
# -
# -
# -
# -
# -

# list



# -         ----------------------------------------->                     -
                

In [1]:
import numpy as np

In [4]:
z1=np.zeros(10)
z1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
z1.dtype

dtype('float64')

In [11]:
zint1=np.zeros(10,dtype='int64')
zint1.dtype

dtype('int64')

In [5]:
o1=np.ones(7)
o1

array([1., 1., 1., 1., 1., 1., 1.])

In [15]:
l1=[1,20,45,6,7,8,9,29]

arr1=np.array(l1,dtype='int64')
arr1

array([ 1, 20, 45,  6,  7,  8,  9, 29])

In [16]:
print(arr1.dtype)

int64


In [17]:
arr1.ndim

1

In [18]:
l1=[ [1,2],[3,4],[5,6] ]


arr2d=np.array(l1,dtype='int64')
arr2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
arr2d.ndim

2

In [20]:
arr2d.shape

(3, 2)

In [21]:
arr2ddirect=np.array([ [1,2],[3,4],[5,6] ],dtype='int64')
arr2ddirect

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
arr2d[0] #0th row

array([1, 2])

In [24]:
arr2d[1] #1st row

array([3, 4])

In [25]:
arr2d[2][1] #row 2 column 1

6

In [26]:
arr2d[2,0]

5

In [28]:
arr2d[ : ,   0]                     #all rows, 0th column

array([1, 3, 5])

In [29]:
temp=np.array([
    
    [1,2,3,4],
    [10,20,30,40],
    [111,222,333,444]
    
])
temp

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [111, 222, 333, 444]])

In [30]:
temp[   1    ,  1:3      ]

array([20, 30])

In [31]:
temp[   0:2   ,  2:3      ]

array([[ 3],
       [30]])

In [32]:
temp.shape

(3, 4)

In [33]:
temp.size #number of elements

12

In [ ]:
# 2,6

1,12


4,3

6,2

12,1

In [34]:
np.reshape(temp, ( 6,2 )   )

array([[  1,   2],
       [  3,   4],
       [ 10,  20],
       [ 30,  40],
       [111, 222],
       [333, 444]])

In [35]:
np.reshape(temp, ( 12,1 )   )

array([[  1],
       [  2],
       [  3],
       [  4],
       [ 10],
       [ 20],
       [ 30],
       [ 40],
       [111],
       [222],
       [333],
       [444]])

In [ ]:
2*3       3*1

In [36]:
temp

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [111, 222, 333, 444]])

In [37]:
temp+temp #addition

array([[  2,   4,   6,   8],
       [ 20,  40,  60,  80],
       [222, 444, 666, 888]])

In [38]:
temp*temp

array([[     1,      4,      9,     16],
       [   100,    400,    900,   1600],
       [ 12321,  49284, 110889, 197136]])

In [39]:
temp

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [111, 222, 333, 444]])

In [40]:
other=np.reshape(temp, ( 12,1 )   )
other

array([[  1],
       [  2],
       [  3],
       [  4],
       [ 10],
       [ 20],
       [ 30],
       [ 40],
       [111],
       [222],
       [333],
       [444]])

In [43]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2,3])

In [44]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2

# [1, 2, 3][1, 2, 3]
# [4, 5, 6][1, 2, 3]

array([1, 2, 3])

In [46]:
arr1+arr2

array([[2, 4, 6],
       [5, 7, 9]])

In [41]:
temp+other

ValueError: operands could not be broadcast together with shapes (3,4) (12,1) 